name: monarch_http
description: Http utilities.
version: 0.1.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.1
  monarch_utils: ^0.1.0

dev_dependencies:
  pedantic: ^1.9.0
