name: monarch_http_server
description: Utilities for http servers.
version: 0.1.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.1.0
  stack_trace: ^1.10.0
  monarch_utils: ^0.1.0

dev_dependencies:
  pedantic: ^1.9.0
